# Generated by Django 5.0.6 on 2024-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flan', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
