# Generated by Django 5.0.6 on 2024-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flan', '0003_flan_vegan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muffins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('short_name', models.SlugField()),
                ('is_private', models.BooleanField()),
                ('vegan', models.BooleanField(default=False)),
            ],
        ),
    ]
