# Generated by Django 5.0.6 on 2024-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flan', '0004_muffins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('image_address', models.URLField()),
            ],
        ),
    ]
