# Generated by Django 5.0.6 on 2024-07-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flan', '0005_sucursal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flan',
            new_name='FlanForm',
        ),
    ]
